version: "3.9"

services:
  mlflow:
    image: python:3.10-slim
    container_name: mlflow_server
    working_dir: /mlflow
    volumes:
      - .:/mlflow
    command: >
      sh -c "pip install mlflow &&
             mlflow ui --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"

  fastapi:
    build: .
    container_name: churn_api
    depends_on:
      - mlflow
    ports:
      - "8001:8001"
